# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: Cargo Format
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        types: [ file, rust ]
        language: system
        pass_filenames: false
