cores = 1
use_honggfuzz = false
deployer_address = "5C62Ck4UrFPiBtoCmeSrgF7x9yv9mn38446dhCpsi2mLHiFT"
max_messages_per_exec = 4
report_path = "output/coverage_report"
fuzz_origin = false
storage_deposit_limit = "100000000000"
verbose = true
fuzz_output = "output_for_integration_test"

[default_gas_limit]
ref_time = 100000000000
proof_size = 3145728

[instrumented_contract_path]
path = "just_a_random_path"
