# Phink Configuration

cores = 10 # set it to 1 for single-core
max_messages_per_exec = 4
report_path = "output/phink/contract_coverage"
use_honggfuzz = false # obligatory for MacOS users
fuzz_origin = false
deployer_address = "5C62Ck4UrFPiBtoCmeSrgF7x9yv9mn38446dhCpsi2mLHiFT" # Alice (Origin(1))
constructor_payload = "9BAE9D5E5C1100007B000000ACAC0000CC5B763F7AA51000F4BD3F32F51151FF017FD22F9404D0308AFBDB3DE6F2E030E23910AC7DCDBB41BC52F1F2F923E49BAF32E9587DCD4D43D50408B62431D7B79C1A506DBEC4785423DDF36E66E2BEBA6CFEFCDD4F5708DFA3388E48"
storage_deposit_limit = "100000000000" # this is commented by default, to set is to `None`
instantiate_initial_value = "0"
verbose = true
instrumented_contract_path = {path = "instrumented_output/"}

[default_gas_limit]
ref_time = 100000000000
proof_size = 3145728  # 3 * 1024 * 1024
