[book]
title = "Phink Book"
authors = ["Kevin Valerio"]
description = "Documentation for Phink fuzzer"
language = "en"
src = "src"
multilingual = false

[rust]
edition = "2021"

[build]
build-dir = "documentation"
create-missing = true
use-default-preprocessors = true


[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/srlabs/phink/"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/srlabs/phink/blob/main/src/{path}"
site-url = "/example-book/"
cname = "myproject.rs"

[output.html.search]
limit-results = 15

[output.html.playground]
editable = false