name: Rust (build, integration tests, formating)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_THREADS: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM and Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main" | sudo tee -a /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get install -y llvm-19 llvm-19-dev clang-19 libclang-19-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-08-13
          components: rustfmt, rust-src
          override: true

      - name: Install required tools
        run: |
          cargo install --force ziggy cargo-afl honggfuzz grcov cargo-contract

      - name: Run afl-system-config
        run: |
          curl https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/afl-system-config > afl-system-config.sh
          chmod +x afl-system-config.sh
          bash afl-system-config.sh

      - name: Run rustfmt checks
        run: cargo fmt -- --check

      - name: Build in release mode
        run: cargo build --release --verbose

      - name: Run AFL++ configuration
        run: cargo afl config --build --plugins --verbose --force

      - name: Compile samples in `sample`
        working-directory: ./sample
        run: bash build.sh

      - name: Run unit tests and integration tests
        run: cargo test --verbose