name: Rust (fmt, test, build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_THREADS: "1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
        
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test  --test cli_instrument_integration_test 
      ### todo: add other integration tests
    - name: Run rustfmt
      run: cargo fmt -- --check
